#!/usr/bin/env node
/**
 * basic XOR cipher
 *
 * Author: Dave Eddy <dave@daveeddy.com>
 * Date: August 13, 2016
 * License: MIT
 */

var fs = require('fs');

var xor = +process.argv[2] || 23;

var input = fs.readFileSync('/dev/stdin', 'ascii').trim();
var output = '';

for (var i = 0; i < input.length; i++) {
  var originalCharacter = input[i];
  var newCharacter;

  switch (originalCharacter) {
    case ' ':
    case '.':
      // skip '.' and ' '
      newCharacter = originalCharacter;
      break;
    default:
      var originalCharacterCode = originalCharacter.charCodeAt(0);
      var newCharacterCode = originalCharacterCode ^ xor;
      var newCharacter = String.fromCharCode(newCharacterCode);
      break;
  }
  output += newCharacter;
}

console.log(output);
